version: '2'
services:
    japp-app:
        image: japp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://japp-mysql:3306/japp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    japp-mysql:
        extends:
            file: mysql.yml
            service: japp-mysql
